### ISSUE TITLE
error: The bottom information cannot be displayed in the production environment (generate)

### ISSUE THREAD

**Issue by rhyme-qing** [Jiangxue-team/jiangxue.design#1]
In the development process (dev) environment, the bottom information, that is, the content in `layouts/common/bottom/index.vue` can be displayed normally, but if it is in the generate environment, it cannot be displayed.

Although @XiaoLi-sach  told me that I can read the documentation of the vite-plugin-vue-setup-extend plugin, but according to the information listed on the official website:

```
<template>
   <div>hello world {{ a }}</div>
</template>

<script lang="ts" setup name="App">
   const a = 1
</script>
```

Such a piece of code, I also used it in `layouts/common/bottom/index.vue` and `layouts/common/header/index.vue`

```
<script setup name="bottom">
// Use the useAsyncData function to initiate an asynchronous request
const { data: equalQuery } = await useAsyncData("equal2", () => {
   // Return the data in the /more directory, or (.where({ director: 'Hayao Miyazaki' }) to filter)
   return queryContent("more/").find();
});
</script>
```

But he still has a problem, but I don't know much about nuxt3, I hope I can get a solution

**Comment by XiaoLi-sach** [comment]
在最新的提交中已解决该问题
